# Docker Compose file for Dinetap AI

services:
  # Backend Service
  backend:
    image: ${DOCKER_USERNAME}/dinetap-backend:latest
    container_name: dinetap-backend
    restart: unless-stopped
    ports:
      - "3036:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb+srv://riqyuzet:ytb060AnxtTyCHfw@cluster0.49ler1o.mongodb.net/dinetap?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=a8d9e7f6c5b4a3d2e1f0c9b8a7d6e5f4c3b2a1d0e9f8c7b6a5d4e3f2c1b0a9d8
      - JWT_EXPIRES_IN=7d
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FRONTEND_URL=https://e2425-wads-l4ccg4-client.csbihub.id
      - ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000,https://e2425-wads-l4ccg4-client.csbihub.id,http://e2425-wads-l4ccg4-client.csbihub.id
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - MAX_FILE_SIZE=5242880
      - UPLOAD_PATH=uploads/
    volumes:
      - backend_uploads:/app/uploads

    networks:
      - dinetap-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Service
  frontend:
    image: ${DOCKER_USERNAME}/dinetap-frontend:latest
    container_name: dinetap-frontend
    restart: unless-stopped
    ports:
      - "3035:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://10.25.143.17:3036/api
      - NEXT_PUBLIC_BACKEND_HEALTH_URL=http://backend:5000/health
      - NEXTAUTH_SECRET=a8d9e7f6c5b4a3d2e1f0c9b8a7d6e5f4c3b2a1d0e9f8c7b6a5d4e3f2c1b0a9d8
      - NEXTAUTH_URL=https://e2425-wads-l4ccg4-client.csbihub.id
      - MONGODB_URI=mongodb+srv://riqyuzet:ytb060AnxtTyCHfw@cluster0.49ler1o.mongodb.net/dinetap?retryWrites=true&w=majority&appName=Cluster0
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_APP_NAME=Dinetap AI
      - NEXT_PUBLIC_APP_VERSION=1.0.0
      - NEXT_PUBLIC_APP_DESCRIPTION=AI-Powered Restaurant Ordering Platform
      - NEXT_PUBLIC_ENABLE_AI_FEATURES=true
      - NEXT_PUBLIC_ENABLE_ANALYTICS=true
      - NEXT_PUBLIC_ENABLE_DEBUG=false
    depends_on:
      - backend
    networks:
      - dinetap-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend_uploads:

networks:
  dinetap-network:
    driver: bridge
